package com.aiqa.guide;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletOutputStream;
import jakarta.servlet.WriteListener;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpServletResponseWrapper;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;

/**
 * Injects the TEJAS product-guide chatbot into Auravis HTML pages.
 * Voice v2 adds explicit recording state, editable transcripts, safer error handling and optional speech output.
 * @author Tejas Shah
 */
@Component
@Order(Ordered.LOWEST_PRECEDENCE - 20)
public class TejasGuideFilter extends OncePerRequestFilter {
    @Override protected boolean shouldNotFilter(HttpServletRequest request) {
        if (!"GET".equalsIgnoreCase(request.getMethod())) return true;
        String path=request.getRequestURI();
        return !("/".equals(path)||"/index.html".equals(path)||"/auravis.html".equals(path)||"/dashboard.html".equals(path)||"/execution-center.html".equals(path));
    }
    @Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain) throws ServletException,IOException {
        BufferingResponse wrapped=new BufferingResponse(response); chain.doFilter(request,wrapped);
        String html=wrapped.body(); if(html.contains("</body>")) html=html.replace("</body>",widget()+"</body>"); copyResponse(response,html);
    }
    private void copyResponse(HttpServletResponse response,String html)throws IOException{byte[] bytes=html.getBytes(StandardCharsets.UTF_8);response.setContentLength(bytes.length);response.setContentType("text/html;charset=UTF-8");response.getOutputStream().write(bytes);}
    private String widget(){return """
<style>
#tejas-launch{position:fixed;right:22px;bottom:22px;z-index:9998;width:58px;height:58px;border-radius:50%;border:1px solid rgba(53,230,173,.55);background:radial-gradient(circle at 35% 30%,#35e6ad,#299fff 48%,#5937b7);box-shadow:0 10px 34px rgba(41,159,255,.35);color:#07111f;font-size:24px;font-weight:900;cursor:pointer}
#tejas-panel{position:fixed;right:22px;bottom:92px;z-index:9999;width:min(390px,calc(100vw - 28px));height:540px;display:none;grid-template-rows:auto auto 1fr auto;background:#0b1829;border:1px solid #234469;border-radius:18px;box-shadow:0 22px 70px rgba(0,0,0,.45);overflow:hidden;color:#f2f7ff;font-family:Inter,system-ui,Arial}#tejas-panel.open{display:grid}
#tejas-head{display:flex;justify-content:space-between;align-items:center;padding:14px 15px;background:linear-gradient(135deg,#102b49,#10213a);border-bottom:1px solid #234469}.tejas-brand{display:flex;gap:10px;align-items:center}.tejas-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle at 35% 30%,#35e6ad,#299fff 50%,#5937b7);color:#07111f;font-weight:1000}.tejas-name{font-weight:900}.tejas-sub{font-size:10px;color:#9bb0cc}.tejas-head-actions{display:flex;gap:4px}.tejas-icon{background:transparent!important;color:#cfe2f8!important;border:0!important;font-size:18px!important;padding:5px 7px!important;cursor:pointer}
#tejas-voice-status{display:flex;align-items:center;gap:7px;padding:7px 14px;background:#081425;border-bottom:1px solid #173755;color:#9bb0cc;font-size:10px}.voice-dot{width:7px;height:7px;border-radius:50%;background:#35e6ad}.voice-dot.listening{background:#fb7185;box-shadow:0 0 0 4px rgba(251,113,133,.15)}
#tejas-messages{padding:14px;overflow:auto;display:flex;flex-direction:column;gap:10px}.tejas-msg{max-width:88%;padding:10px 12px;border-radius:12px;line-height:1.45;font-size:13px;white-space:pre-wrap}.tejas-bot{align-self:flex-start;background:#132743;border:1px solid #234469}.tejas-user{align-self:flex-end;background:#173755;border:1px solid #2b5f91}.tejas-quick{display:flex;gap:6px;flex-wrap:wrap;margin-top:6px}.tejas-quick button{background:#102b49!important;color:#cfe2f8!important;border:1px solid #234469!important;border-radius:999px!important;padding:7px 9px!important;font-size:11px!important}
#tejas-inputbar{display:grid;grid-template-columns:1fr auto auto;gap:7px;padding:11px;border-top:1px solid #234469;background:#081425}#tejas-input{border:1px solid #234469;background:#0b1829;color:#f2f7ff;border-radius:10px;padding:10px 11px;min-width:0}#tejas-send,#tejas-mic{border:0;border-radius:10px;padding:9px 11px;font-weight:900;background:linear-gradient(90deg,#35e6ad,#299fff);color:#07111f;cursor:pointer}#tejas-mic.listening{background:#fb7185;box-shadow:0 0 0 3px rgba(251,113,133,.25)}
@media(max-width:600px){#tejas-launch{right:14px;bottom:14px}#tejas-panel{right:14px;bottom:82px;height:min(570px,76vh)}}
</style>
<button id="tejas-launch" title="Open TEJAS — Auravis Guide" aria-label="Open TEJAS guide">T</button>
<section id="tejas-panel" aria-label="TEJAS Auravis product guide"><div id="tejas-head"><div class="tejas-brand"><div class="tejas-avatar">T</div><div><div class="tejas-name">TEJAS</div><div class="tejas-sub">AI Product Guide • Voice v2</div></div></div><div class="tejas-head-actions"><button class="tejas-icon" id="tejas-sound" title="Voice responses on">🔊</button><button class="tejas-icon" id="tejas-close" aria-label="Close">×</button></div></div><div id="tejas-voice-status"><span id="tejas-voice-dot" class="voice-dot"></span><span id="tejas-voice-text">Voice ready — tap microphone to dictate</span></div><div id="tejas-messages"></div><div id="tejas-inputbar"><input id="tejas-input" autocomplete="off" placeholder="Ask about Auravis…"><button id="tejas-mic" title="Start voice input">🎙</button><button id="tejas-send">Send</button></div></section>
<script>(()=>{
const $=id=>document.getElementById(id),panel=$('tejas-panel'),launch=$('tejas-launch'),close=$('tejas-close'),msgs=$('tejas-messages'),input=$('tejas-input'),send=$('tejas-send'),mic=$('tejas-mic'),sound=$('tejas-sound'),voiceText=$('tejas-voice-text'),voiceDot=$('tejas-voice-dot'),page=location.pathname;let soundOn=true,listening=false,recognition=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const add=(text,who='bot')=>{const d=document.createElement('div');d.className='tejas-msg '+(who==='user'?'tejas-user':'tejas-bot');d.innerHTML=esc(text);msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d};
const status=(text,isListening=false)=>{voiceText.textContent=text;voiceDot.classList.toggle('listening',isListening);mic.classList.toggle('listening',isListening);mic.textContent=isListening?'■':'🎙';mic.title=isListening?'Stop voice input':'Start voice input'};
const say=text=>{if(!soundOn||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-IN';u.rate=.95;speechSynthesis.speak(u)}catch(e){}};
const intro=()=>{let hint='I can explain the roadmap, architecture, RAG, test generation, execution, agents and self-healing.';if(page.includes('auravis'))hint='Upload a business requirement and provide a UAT target. I can explain what Auravis will do next.';if(page.includes('dashboard'))hint='This dashboard shows requirements, missions, technology, traffic and execution progress.';if(page.includes('execution-center'))hint='This page manages UAT targets and execution evidence.';const d=add('Hi, I’m TEJAS — your Auravis product guide. '+hint);const q=document.createElement('div');q.className='tejas-quick';['How do I start?','Explain roadmap','What is RAG?','What is M5?','What is M6?'].forEach(x=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>ask(x);q.appendChild(b)});d.appendChild(q)};
const answer=q=>{const x=q.toLowerCase();if(x.includes('start')||x.includes('upload'))return 'Start from New Mission. Upload a business requirement, provide the UAT application URL, then Auravis analyzes requirements, retrieves knowledge, generates tests and executes supported UAT flows.';if(x.includes('rag')||x.includes('knowledge'))return 'RAG means Retrieval-Augmented Generation. Auravis retrieves relevant persisted project knowledge before requirement and test reasoning.';if(x.includes('roadmap'))return 'Auravis roadmap runs from M1 Autonomous Mission through M8 Autonomous CI/CD Quality Gate. M5 adds agentic orchestration and M6 focuses on safe self-healing.';if(x.includes('m5')||x.includes('agent'))return 'M5 introduces specialized agents coordinated through a controlled Java orchestration layer, with persisted activity for auditability.';if(x.includes('m6')||x.includes('heal'))return 'M6 classifies recoverable automation failures, evaluates safe healing candidates, applies confidence gates and preserves a healing audit trail.';if(x.includes('playwright')||x.includes('execution'))return 'Auravis uses Playwright for deterministic browser execution while Java controls permitted actions, assertions, retries and evidence capture.';if(x.includes('technology')||x.includes('tech stack'))return 'Auravis combines Java, Spring Boot, REST APIs, PostgreSQL, RAG, AI agents, Playwright, Docker, GitHub Actions, AWS EC2, Nginx and browser speech capabilities.';if(x.includes('openai'))return 'Auravis supports OpenAI-compatible integration with deterministic fallback. Credentials are not exposed in the UI.';if(x.includes('tejas')||x.includes('who are you'))return 'I’m TEJAS, the built-in Auravis product guide. I explain the product and workflow and remain separate from the autonomous QA agents.';return 'I can guide you through Auravis usage, technology, roadmap, RAG, test generation, execution, M5 agents and M6 self-healing.'};
const ask=q=>{q=(q||input.value).trim();if(!q)return;add(q,'user');input.value='';status('Processing your question…');const a=answer(q);setTimeout(()=>{add(a);say(a);status('Voice ready — tap microphone to dictate')},120)};
launch.onclick=()=>{panel.classList.add('open');if(!msgs.children.length)intro();input.focus()};close.onclick=()=>{if(listening&&recognition)recognition.stop();panel.classList.remove('open')};send.onclick=()=>ask();input.addEventListener('keydown',e=>{if(e.key==='Enter')ask()});sound.onclick=()=>{soundOn=!soundOn;if(!soundOn&&'speechSynthesis'in window)speechSynthesis.cancel();sound.textContent=soundOn?'🔊':'🔇';sound.title=soundOn?'Voice responses on':'Voice responses off'};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){mic.disabled=true;mic.style.opacity='.45';status('Voice input is not supported by this browser — text chat is available.')}else{recognition=new SR();recognition.lang='en-IN';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;let finalText='';recognition.onstart=()=>{listening=true;finalText='';status('Listening… tap ■ when finished',true)};recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=(finalText?' ':'')+t.trim();else interim+=t}input.value=(finalText+(interim?' '+interim:'')).trim();status(interim?'Listening… '+interim.trim():'Listening… tap ■ when finished',true)};recognition.onend=()=>{listening=false;status(input.value.trim()?'Transcript ready — review/edit, then press Send':'Voice ready — tap microphone to dictate')};recognition.onerror=e=>{listening=false;const messages={'not-allowed':'Microphone permission denied. Allow microphone access in browser settings.','service-not-allowed':'Speech service is blocked by the browser.','no-speech':'No speech detected. Tap the microphone and try again.','audio-capture':'No microphone was detected.','network':'Speech recognition network error. Please retry.'};status(messages[e.error]||('Voice recognition error: '+e.error))};mic.onclick=()=>{if(listening){try{recognition.stop()}catch(e){}return}try{if('speechSynthesis'in window)speechSynthesis.cancel();recognition.start()}catch(e){status('Unable to start microphone. Please wait a moment and retry.')}}}
})();</script>
""";}
    private static final class BufferingResponse extends HttpServletResponseWrapper{private final ByteArrayOutputStream buffer=new ByteArrayOutputStream();private PrintWriter writer;BufferingResponse(HttpServletResponse r){super(r);}@Override public ServletOutputStream getOutputStream(){return new ServletOutputStream(){@Override public boolean isReady(){return true;}@Override public void setWriteListener(WriteListener l){}@Override public void write(int b){buffer.write(b);}};}@Override public PrintWriter getWriter(){if(writer==null)writer=new PrintWriter(new OutputStreamWriter(buffer,StandardCharsets.UTF_8));return writer;}String body(){if(writer!=null)writer.flush();return buffer.toString(StandardCharsets.UTF_8);}}
}
